export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Projects } from "./Projects"
export { default as Social } from "./Social"
export { default as Footer } from "./Footer"
